"""initial migration

Revision ID: 90675fd0f77b
Revises: 991dd56a6996
Create Date: 2017-03-17 15:57:48.465201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90675fd0f77b'
down_revision = '991dd56a6996'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('default', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_roles_default'), 'roles', ['default'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roles_default'), table_name='roles')
    op.drop_column('roles', 'default')
    # ### end Alembic commands ###
